language: python
env:
  - KERAS_BACKEND=tensorflow
  - KERAS_BACKEND=theano BLAS_LIB=OpenBLAS
python:
  - 2.7
  - 3.6
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
before_install:
  - if [[ "$KERAS_BACKEND" == "theano" ]]; then
      sudo apt-get update && sudo apt-get install libopenblas-base libopenblas-dev -y;
    fi
install:
  - pip install --upgrade pip
  - if [[ "$KERAS_BACKEND" == "theano" ]]; then
      pip install -r requirements-theano.txt;
    else
      pip install -r requirements.txt;
    fi
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install keras-self-attention
before_script:
  - bash lint.sh
script:
  - bash test.sh
after_success:
  coveralls
