language: python
env:
  matrix:
    - BLAS_LIB=OpenBLAS
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenblas-base libopenblas-dev -y
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install keras-self-attention
before_script:
  - bash lint.sh
script:
  - bash test.sh
after_success:
  coveralls
